# Generated by Django 5.0.7 on 2024-07-23 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planName', models.CharField(default=None, max_length=15, unique=True)),
                ('planPrice', models.IntegerField(default=None)),
                ('planDuration', models.IntegerField(default=None)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=15, unique=True)),
                ('firstName', models.CharField(default=None, max_length=10)),
                ('lastName', models.CharField(default=None, max_length=10)),
                ('email', models.EmailField(default=None, max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=15)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='app.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='users',
            field=models.ManyToManyField(related_name='user', to='app.user'),
        ),
    ]
